/// Template for a journal entry
pub fn journal_entry(date: &str, title: &str) -> String {
    format!(
        r#"# {title}

**Date:** {date}

## Summary

<!-- Brief overview of this audit cycle -->

## Key Findings

<!-- Numbered list of findings from this cycle -->

## Cross-repo Observations

<!-- How are main and QC interacting? -->

## Blind Spots Identified

<!-- What did the orchestrators miss? -->

## Recommendations Filed

<!-- List of audit-outbound issues created this cycle -->

## Reflections

<!-- Meta-observations about the audit process itself -->

## Tags

<!-- Comma-separated tags for indexing, e.g.: cross-repo, blind-spots, self-improvement -->
"#
    )
}

/// Template for a worklog entry
pub fn worklog_entry(date: &str, cycle: u32, summary: &str) -> String {
    let summary_line = if summary.is_empty() {
        "<!-- Brief summary -->".to_string()
    } else {
        summary.to_string()
    };

    format!(
        r#"# Worklog: {date} — Cycle {cycle}

**Summary:** {summary_line}

## Steps Performed

<!-- Ordered list of actions taken -->

## Issues Created

<!-- List of issues filed this cycle -->

## State Changes

<!-- Changes to state.json -->

## Time & Efficiency

<!-- Notes on cycle efficiency, wasted turns, permission issues -->

## Next Cycle Priorities

<!-- What should the next cycle focus on? -->
"#
    )
}

/// Header for the JOURNAL.md index
pub fn index_header() -> &'static str {
    r#"# Journal

Reflective log for the audit orchestrator. Entries in [`docs/journal/`](docs/journal/).

*Auto-generated by `audit-journal index`. Do not edit manually.*
"#
}
